##############################################################################
# ScaleIO task groups
##############################################################################      
# for next version:
# - id: scaleio-storage-tier1
#   type: group
#   role: [scaleio-storage-tier1]
#   tasks: [hiera, globals, tools, logging, netconfig, hosts, firewall, deploy_start]
#   required_for: [deploy_end]
#   requires: [deploy_start]
#   parameters:
#     strategy:
#       type: parallel
# 
# - id: scaleio-storage-tier2
#   type: group
#   role: [scaleio-storage-tier2]
#   tasks: [hiera, globals, tools, logging, netconfig, hosts, firewall, deploy_start]
#   required_for: [deploy_end]
#   requires: [deploy_start]
#   parameters:
#     strategy:
#       type: parallel

##############################################################################
# ScaleIO environment check
##############################################################################
- id: scaleio-environment-check
#  groups: [scaleio-storage-tier1, scaleio-storage-tier2, primary-controller, controller, compute, cinder]
  groups: [primary-controller, controller, compute, cinder]
  required_for: [deploy_end, hosts]
  requires: [deploy_start] #, netconfig]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/environment.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600


##############################################################################
# ScaleIO prerequisites tasks
##############################################################################      
- id: scaleio-environment
#  role: [scaleio-storage-tier1, scaleio-storage-tier2, primary-controller, controller, compute, cinder]
  role: [primary-controller, controller, compute, cinder]
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/environment.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: scaleio-environment-existing-mdm-ips
#  role: [scaleio-storage-tier1, scaleio-storage-tier2, primary-controller, controller, compute, cinder]
  role: [primary-controller, controller, compute, cinder]
  required_for: [post_deployment_end]
  requires: [scaleio-environment]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/environment_existing_mdm_ips.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600


##############################################################################
# ScaleIO cluster tasks
##############################################################################
- id: scaleio-mdm-packages
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [scaleio-environment-existing-mdm-ips]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/mdm_package.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: scaleio-discover-cluster
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [scaleio-mdm-packages]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/discovery_cluster.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: scaleio-resize-cluster
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [scaleio-discover-cluster]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/resize_cluster.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
    
- id: scaleio-mdm-server
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [scaleio-resize-cluster]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/mdm_server.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: scaleio-gateway-server
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [scaleio-mdm-server]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/gateway_server.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: scaleio-sds-server
#  role: [scaleio-storage-tier1, scaleio-storage-tier2]
  role: [primary-controller, controller, compute]
  required_for: [post_deployment_end]
  requires: [scaleio-gateway-server, scaleio-environment-existing-mdm-ips]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sds_server.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800
    
- id: scaleio-sdc-server
  required_for: [post_deployment_end]
  requires: [scaleio-sds-server, scaleio-environment-existing-mdm-ips]
  role: [primary-controller, controller, compute, cinder]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sdc_server.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: scaleio-sdc
  required_for: [post_deployment_end]
  requires: [scaleio-sdc-server]
  role: [primary-controller, controller, compute, cinder]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sdc.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: scaleio-configure-cluster
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [scaleio-sdc]
  cross-depends:
    - name: scaleio-sds-server
    - name: scaleio-sdc
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/cluster.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800


##############################################################################
# ScaleIO OS tasks
##############################################################################
- id: scaleio-compute
  required_for: [post_deployment_end]
  requires: [scaleio-configure-cluster]
  role: [compute]
  cross-depends:
    - name: scaleio-configure-cluster
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/nova.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: scaleio-cinder
  required_for: [post_deployment_end]
  requires: [scaleio-configure-cluster]
  cross-depends:
    - name: scaleio-configure-cluster
  role: [cinder]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/cinder.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: scaleio-glance
  required_for: [upload_cirros, post_deployment_end]
  requires: [scaleio-cinder]
  cross-depends:
    - name: scaleio-cinder
    - name: upload_cirros
  role: [primary-controller, controller]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/glance.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
